name: test-program
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: start
        run: echo ===START TEST===  
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Lint
        run: go fmt $(go list ./... | grep -v /vendor/)
      - name: Build philos
        run: mkdir -p bin && go build -o bin ./...
      - name: Test
        run: |
          echo === Test invalid args ===
          ./bin/philo-go
          ./bin/philo-go 5 610 200 200 5 1 3
          ./bin/philo-go -5 =610 -200 -200 5
          ./bin/philo-go asd 610 200 200 10
          ./bin/philo-go 5 610 200
          echo === Philo should die ===
          ./bin/philo-go 1 600 200 200
          ./bin/philo-go 2 610 300 320 5
          ./bin/philo-go 3 610 310 301 5
          echo ==== Normal RUNS ====
          ./bin/philo-go 2 410 200 200 3
          ./bin/philo-go 5 610 200 200 5
      - name: end
        run: pwd && ls -l && echo ====END TEST====
  
